from typing import Protocol


class AIProvider(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def generate_json(self, prompt: str, task: str = "extraction", schema: dict | None = None) -> dict: ...
    def generate_text(self, prompt: str, task: str = "study") -> str: ...
